version: '3'
services:
  database:
    image: eventuateio/eventuate-postgres:$EVENTUATE_COMMON_VERSION
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: eventuate
      POSTGRES_PASSWORD: eventuate

