
deployUrl=file:///Users/cer/.m2/testdeploy
dockerComposePluginVersion=0.17.6

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

springBootVersion=3.4.7


eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.20.0.BUILD-SNAPSHOT
eventuateTramVersion=0.38.0.BUILD-SNAPSHOT
eventuatePlatformVersion=2026.1.BUILD-SNAPSHOT

messageBroker=kafka
database=mysql
mode=

