logging:
  level:
    io:
      eventuate: DEBUG

server.port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DOCKER_HOST_IP:localhost}/eventuate
    username: mysqluser
    password: mysqlpw
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  profiles: postgres
  datasource:
    url: jdbc:postgresql://${DOCKER_HOST_IP:localhost}/eventuate
    username: eventuate
    password: eventuate
    driver-class-name: org.postgresql.Driver

